### ISSUE TITLE
G27 sequential shifter modification

### ISSUE THREAD

**Issue by JamesCoyle** [chrisjansson/Shifter#1]
This really isn't the place for this but as github doesn't have a messaging system I don't know how else to contact you. You seem to have an understanding of the hardware so I'm hoping you may be able to give some insight. 

I've noticed the G27 appears to have basically the exact same hardware as the G25 minus a new top housing and the lack of the sequential shifting hardware (the bit that locks the stick to 3rd and 4th only). I've also noticed that shorting the place on the PCB where the third wire should connect changes all shifter positions to be either 1st or 2nd depending on if the shifter is forward or backward. 

Do you know if there is any way to actually make this useful? I don't have enough knowledge of the circuitry or the signals sent to the main unit to figure out if this 1st or 2nd can be interpreted by the G27 as buttons 4 and 5 (the flappy paddles). That would then make it a simple case of wiring in a switch to toggle the shifter to be sequential.

**Comment by chrisjansson** [comment]
Hiya, 

The reason why shorting pin 3 causes all gears to read as 1st or 2nd is because the gear selection is determined by reading two potentiometers, x (column 1/2, 3/4, 5/6) and y axi (rows 1/3/5, 2/4/6). Shorting the x potentionmeter makes the wheel believe that the gear stick is all the way to the left.

As I understand it you want to use the G27 shifter as a sequential one?

 I think it will help to know that the only difference in the G25 shifter when it is in sequential mode is that it is locked to 3/4 and recenters (I believe that there also is a button that signals wether the shifter is in sequential mode or not in the hardware, I can't recall if it's used for anything though). The consequence of this is that you need two button mappings in games, one sequential and one h-patterned. Or to (sort of) answer your question, the G25 in sequential mode is not interpreted as button 4/5 but rather the same buttons as gear 3/4. So the easiest way to make it work as a sequential stick is to make a bracket that limits the stick travel.

There is no simple way of having the G27 (or G25 for that matter) send stick positions as buttons 4/5. The reason is because of the potentiometers, the selected gear is determined by the main unit by reading the potentiometers as an (x, y) pair. 

The simplest way to imitate that behavior would be to create a software macro that presses a virtual button (shift down) whenever button 4 or gear 3 is selected on the G27. 

Sorry for the raggedy ass formulation, I'll try to clarify if it's unintelligible.

Cheers

**Comment by JamesCoyle** [comment]
Ideally I'd like a simple flip switch to toggle the mode from individual gears to 1-3-5 trigger the right paddle and 2-4-6 trigger the left. For some situations it would be nice to be able to use the shifter sequentially rather than using paddles (rally or drifting are prime examples as the paddles are never where you left them) but I don't want to make it permanent. I can deal with not limiting the motion of the stick and having to manually recenter it (unless I can figure out a decent solution) but I don't want to be constantly rebinding controls. 

I forgot to take a picture while I had it open but thankfully the internet already has a few. This is the place I assume the G25 has a connector to the locking mechanism. 
![image](https://cloud.githubusercontent.com/assets/10384436/16858052/0a46bf92-4a1c-11e6-9ad7-56681bae7cfb.png)
My assumption was that enabling that data line somehow changed the data the shifter sent to the wheel unit so it knew to treat those values as the paddles rather than gear selection. Upon testing I found that shorting this connection does in fact change all of the values for gears to 1st or 2nd based on the vertical position. I would have thought (in the G25) it would say the pot value was to be interpreted as the paddles not the physical gears. That would be the logical implementation of such a feature though I guess that may be why it was removed from the G27 as people found it annoying to use. Seems like a pretty dumb way of implementing such a feature if you ask me...

I'm still just learning electronics but have some basic skills and have played with microcontrollers before and could manage adding a few wires and simple circuitry. Looking at your diagram for the G25 board I'd assume S2 (Labeled MODE) is the pin that the sequential switch is wired to which would mean the signal for that gets sent from that shift register to the wheel. Do you know anything about the wheel circuitry? It's probably not possible but I'm hoping that that signal could be detected in the wheel somehow and be used to trigger the paddle signals manually.

**Comment by chrisjansson** [comment]
Yes S2 signals the state of the h/s pattern selection. If the signal is used it's for internal purposes (probably for how the x/y pots should be interpreted), it does not change the behavior of what signals the units sends to the computer though.

To change that behavior of the wheel, you'd either have to reprogram the IC in the main unit that is responsible for reading the pots. Or possibly add another another IC yourself that reads the pots and pulls the paddle inputs on the main unit IC to register as paddle inputs.

I can't see a simple way to achieve it with hardware without adding logic yourself.

As I said before, if all you want is to get rid of the remapping problem, I'd use AutoHotkey for example and map 4th gear to trigger the same button as the right paddle.

**Comment by JamesCoyle** [comment]
Well those two chips are serial shift registers right so as the signal is sent to the chip it must mean it is sent to the main unit. If I could then read that signal in the main unit it is theoretically possible to create a circuit which is enabled when that signal is enabled. That circuit then reads the voltage of the y-axis pot and sends a high signal to the paddle inputs.

It seems to me like this simple circuit would do the trick. The pot voltage is the top one and the enable is the L wire next to the 5V connection. I used a simple not gate to get the 0 volts value and read the 5 volts straight from the pot. 
![image](https://cloud.githubusercontent.com/assets/10384436/16918929/8992f654-4cff-11e6-81da-bacf14001a0b.png)

The tricky part is actually figuring out where in the G27 these connections need to be made. I don't have a circuit diagram or pinouts or anything for the main unit. I don't know how the main unit handles the incoming data or if it would even be possible to intercept it. If not then it would mean looking into ways to send the signal down the wire manually. What does the 5v short do? Could those wires be used?

**Comment by chrisjansson** [comment]
Exactly, the shift registers are however read by the main unit, so you'll have little luck getting hold of the value from the shift register. Scavenging a wire in the d-sub for your enable is easier, you'll have to check that for yourself though.

I can't make sense of your schematic however, I'm not much of an electrical engineer myself.
